### PR TITLE
build: wallet: Fix wallet with boost library >= 1.78

### LINKED ISSUE #932: test failed on boost1.83
Hi,
litecoin 0.21.2.2 has a build failed issue based on boost1.83, the bug is here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059138

After cherry-picking the [commit](https://github.com/bitcoin/bitcoin/pull/22713). The build is ok but the tests failed:

```
2023-12-28T02:55:17.400246Z [test] init message: Verifying wallet(s)...
wallet/test/init_tests.cpp(72): error: in "init_tests/walletinit_verify_walletdir_no_trailing": check walletdir == expected_path has failed
wallet/test/init_tests.cpp(65): Leaving test case "walletinit_verify_walletdir_no_trailing"; testing time: 2284us
wallet/test/init_tests.cpp(75): Entering test case "walletinit_verify_walletdir_no_trailing2"
2023-12-28T02:55:17.401024Z [test] Seed: Setting random seed for current tests to RANDOM_CTX_SEED=25ab916ff4dd121ad739e5a2caeb0397cd2b5b0b1661b25a9fe17e68c0672423
2023-12-28T02:55:17.401045Z [test] Litecoin Core version v0.21.2.2-g953811f77a85cfc79d79e08f2283ddf0b9730928 (release build)
2023-12-28T02:55:17.401106Z [test] Assuming ancestors of block 62e2e3d21343a00994d38a63524867507dbeee6850e8fbf02e9c47a3ccf82f24 have valid signatures.
2023-12-28T02:55:17.401111Z [test] Setting nMinimumChainWork=000000000000000000000000000000000000000000000702edaa57d42a9fd9e2
2023-12-28T02:55:17.401879Z [test] Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2023-12-28T02:55:17.402414Z [test] Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2023-12-28T02:55:17.402531Z [test] Using wallet directory /tmp/test_common_Litecoin Core/0f4dcb1b5c80e8d6c94b33883dffbe821fb28be06a5ada86dfa332b70efad982/wallets/
2023-12-28T02:55:17.402540Z [test] init message: Verifying wallet(s)...
wallet/test/init_tests.cpp(82): error: in "init_tests/walletinit_verify_walletdir_no_trailing2": check walletdir == expected_path has failed
wallet/test/init_tests.cpp(75): Leaving test case "walletinit_verify_walletdir_no_trailing2"; testing time: 2274us

```

OS: Debian sid/unstable on amd64

### PR DESCRIPTION
**Pull request by luke-mckay**
The line that fixes the issue comes from bitcoin#24104. I gated it with the boost library version as I'm not aware if it would be backward compatible or not.
fixes #932

I wasn't sure if I should use "build:" or "wallet:" for the start of the title because it's a wallet change but really only to fix the build for the later boost libraries.  Hopefully using both is acceptable for this case?  Let me know if I should do something different in the future.

### CODE REVIEW

**Comment by luke-mckay** [comment]
This was another one that seemed simple enough.  I didn't want to change default behavior when building with existing dependencies (the older Boost) so I used the compile option to prevent any differences for the builds using the official dependencies, but this allows people to build with the later libraries as well.  I figured it might be useful for others, let me know if there's anything I should have done differently or better.

File: src/wallet/load.cpp [hunk 1]
```diff
@@ -22,7 +22,11 @@ bool VerifyWallets(interfaces::Chain& chain)
         fs::path wallet_dir = gArgs.GetArg("-walletdir", "");
         boost::system::error_code error;
         // The canonical path cleans the path, preventing >1 Berkeley environment instances for the same directory
+#if BOOST_VERSION >= 107800
```
Comment (DavidBurkett) [inline src/wallet/load.cpp:25]: We probably don't need to version gate this. The backward-incompatible change that Boost 1.78 made was to stop removing trailing spaces in canonical. So, pre-1.78, there won't be any trailing spaces, and the call to `remove_trailing_spaces` should be a no-op.

**Review by Dsmccarty78 — APPROVED** [review]
